### ISSUE TITLE
FPS drops when leaving town.

### ISSUE THREAD

**Issue by Kisioj** [eforgacs-games/Dragon_Warrior#4]
![image](https://user-images.githubusercontent.com/6262202/147891848-de83b4d3-c9f5-4f22-83b7-e13befe4fab7.png)
after leaving town , FPS significantly drops.
It was 60 in town and 30 outside.

**Comment by eforgacs** [comment]
Thanks for opening this issue! Yes, that's definitely a challenge I'm working with. I think it has to do with the size of the world map, and all of the tiles being drawn/read into memory, etc. when really it should only be the subset of the tiles that are necessary for the current view. I'm currently in grad school at the moment and this semester has been very busy, but maybe during our summer break I'll get around to fixing this.

**Comment by eforgacs** [comment]
FPS should be improved now. Thanks for reporting this!
